version: '3.8'

services:
  rabbitmq:
      container_name: "rabbitmq"
      image: rabbitmq:3.8-management
      ports: 
        #AMQP port
        - "5672:5672"
        #HTTP management UI
        - "15672:15672"
      networks: 
        - enoch-network
      expose: 
        - 15672
        - 5672

  apienoch: 
      build: 
        context: .
        dockerfile: Dockerfile 
      environment:
        ASPNETCORE_ENVIRONMENT: "Development"
        ASPNETCORE_URLS: http://+:80
        RABBITMQ_QUEUE_NAME: "userQ"
        RABBITMQ_USER: "guest"
        RABBITMQ_HOSTNAME: "localhost"
        RABBITMQ_PASSWORD: "guest"
        RABBITMQ_PORT: "5672"
        AWS_SQS_QUEUE_NAME: "enoch-user_q"
        AWS_SQS_QUEUE_URL: "https://sqs.sa-east-1.amazonaws.com/112131041329/enoch-user_q"
        AWS_ACCESSKEY: "AKIARUG4H5AYXMQA4LVP"
        AWS_SECRET: "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"
        AWS_PROFILE: "thiagoteixeira"
        AWS_QUEUE_MAX_MESSAGES: 1
        AWS_QUEUE_WAIT_TIME: 2
        AWS_BUCKET: "enoch-userpic"
        # ASPNETCORE_Kestrel__Certificates__Default__Password: "AS78xOi3#"
        # ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
      ports: 
        - 5000:80
      depends_on:
        - rabbitmq
      networks: 
          - enoch-network

networks:
    enoch-network:
      driver: bridge